name: Train and Deploy BERT GLUE Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly run for retraining

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/

  train:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ['glue/cola', 'glue/sst2']  # Add more tasks as needed
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train model
        run: python src/train.py
        env:
          TFDS_NAME: ${{ matrix.task }}
          EPOCHS: 3
          BATCH_SIZE: 32
      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.task }}-model
          path: models/

  evaluate:
    needs: train
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ['glue/cola', 'glue/sst2']  # Same tasks as in train job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download model
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.task }}-model
          path: models/
      - name: Evaluate model
        run: python src/evaluate.py
        env:
          TFDS_NAME: ${{ matrix.task }}

  deploy:
    needs: evaluate
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Download all models
        uses: actions/download-artifact@v3
        with:
          path: models/
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yourusername/bert-glue-model:latest